[package]
name = "example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nano_api = { path = "../api" }

[profile.release] ## HEAVY OPTIMIZATION
lto = "fat"
codegen-units = 1
panic = "abort"