[package]
name = "nano_api"
version = "0.1.0"
edition = "2021"

[dependencies]
derive = { path = "../derive" }
postcard = { version = "1.0.10", features = ["alloc"] }
serde = "1.0.209"

[features]
embedded = []
default = ["embedded"]